## Numpy

1. Write a Python program to print the NumPy version in your system

In [3]:
import numpy as np
np.version

<module 'numpy.version' from 'E:\\notebooks\\anaconda\\lib\\site-packages\\numpy\\version.py'>

2. Write a Python program to convert a list of numeric value into a one- dimensional NumPy array.


In [8]:
#list of numeric values
lst = [1,2,3,4,5,6,7]
print(type(lst))
print(lst)

#1-D numpy array
arr = np.array(lst)
print(type(arr))
arr

<class 'list'>
[1, 2, 3, 4, 5, 6, 7]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5, 6, 7])

3. Write a Python program to create an array with values ranging from 12 to 38.

In [12]:
arr1 = np.arange(12,39)
arr1

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

4. Write a Python program to convert a list and tuple into arrays.

In [17]:
#list of numeric values
lst = [1,2,3,4,5,6,7]
print(type(lst))
print(lst)
print('\n')

#tuple of numeric values
tup = (1,2,3,4,5,6,7,8)
print(type(tup))
print(tup)
print('\n')

arr1 = np.array(lst)
print(type(arr1))
print(arr1)
print('\n')

arr2 = np.array(tup)
print(type(arr2))
print(arr2)

<class 'list'>
[1, 2, 3, 4, 5, 6, 7]


<class 'tuple'>
(1, 2, 3, 4, 5, 6, 7, 8)


<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8]


5. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [30]:
arr = np.array([1,2,3,4,5,6])
# type(arr[0])
print("No. of elements of array: ",arr.size)
print("length of one array element in bytes: ", arr.itemsize)
print("total bytes consumed by the elements: ", arr.nbytes)

No. of elements of array:  6
length of one array element in bytes:  4
total bytes consumed by the elements:  24


6. Write a Python program compare two arrays using numpy.

In [35]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([1,2,3,4,5,6])

compar_arr1 = arr1 == arr2
print(compar_arr1.all())

arr3 = np.array([1,2,3,4,5,8])
arr4 = np.array([1,2,3,4,5,6])

compar_arr2 = arr3 == arr4
print(compar_arr2.all())

True
False


7. Write a Python program to get the number of nonzero elements in an array.

In [36]:
arr1 = np.array([1,2,0,3,0,4,5,0,6,0])
cnt=0
for i in arr1:
    if(i!=0):
        cnt = cnt+1
print(cnt)

6


8. Write a Python program to check whether the numpy array is empty or not.

In [41]:
def empty_arr(arr):
    if(arr.size == 0):
        print("Empty")
    else:
        print("Not Empty")
empty_arr(np.array([]))
empty_arr(np.array([1,2,0,3,0,4,5,0,6,0]))

Empty
Not Empty


9. Write a Python program to get the powers of an array values element-wise.

In [42]:
def get_power(arr):
    for i in arr:
        print(np.power(i,3))
get_power(np.array([1,2,3,4,5]))

1
8
27
64
125


10. Write a Python program to stack two arrays: 1) row-wise 2) column-wise
- Arr1 = np.linspace(1,20,50)
- Arr2 = np.linspace(21,40,50)

In [60]:
Arr1 = np.linspace(1,20,50)
Arr2 = np.linspace(21,40,50)
print(np.hstack((Arr1, Arr2)))
print('\n')
print(np.vstack((Arr1, Arr2)))

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.         21.         21.3877551  21.7755102  22.16326531
 22.55102041 22.93877551 23.32653061 23.71428571 24.10204082 24.48979592
 24.87755102 25.26530612 25.65306122 26.04081633 26.42857143 26.81632653
 27.20408163 27.59183673 27.97959184 28.36734694 28.75510204 29.14285714
 29.53061224 29.91836735 30.30612245 30.69387755 31.08163265 31.46938776
 31.85714286 32.24489796 32.63265306 33.02040816 33.

## Pandas (Series and DataFrame)

1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [61]:
import pandas as pd

E:\notebooks\anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
E:\notebooks\anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [62]:
arr1 = np.array([1,2,3,4,5])
print(pd.Series(arr1))

0    1
1    2
2    3
3    4
4    5
dtype: int32


2. Write a Python program to convert a Panda module Series to Python list and its type.

In [64]:
arr1 = np.array([1,2,3,4,5])
s1 = pd.Series(arr1)
lst = list(s1)
print(lst)
print(type(lst))

[1, 2, 3, 4, 5]
<class 'list'>


3. Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [73]:
s1 = pd.Series(data = [1,2,3,4,5])
s2 = pd.Series(data = [12,14,10,9,5])
print("Add: \n", s1.add(s2), '\n')
print("Subtract: \n", s1.subtract(s2), '\n')
print("Multiply: \n", s1.multiply(s2), '\n')
print("Divide: \n", s1.divide(s2), '\n')

Add: 
 0    13
1    16
2    13
3    13
4    10
dtype: int64 

Subtract: 
 0   -11
1   -12
2    -7
3    -5
4     0
dtype: int64 

Multiply: 
 0    12
1    28
2    30
3    36
4    25
dtype: int64 

Divide: 
 0    0.083333
1    0.142857
2    0.300000
3    0.444444
4    1.000000
dtype: float64 



4. Write a Python program to compare the elements of the two Pandas Series

In [74]:
s1 = pd.Series(data = [1,2,3,4,5])
s2 = pd.Series(data = [12,14,10,9,5])
print(s1==s2)

0    False
1    False
2    False
3    False
4     True
dtype: bool


5. Write a Python program to display the following data column wise.

In [77]:
#As there's no data, assuming the data in the form of a dictionary
df = pd.DataFrame(data = {'a': [1,2,3], 'b': [1.2,2.3,4.5], 'c': [3,4,5]})
print(df)

   a    b  c
0  1  1.2  3
1  2  2.3  4
2  3  4.5  5


7. Write a Python program to select the specified columns and rows from a given Data Frame.

In [82]:
df = pd.DataFrame(data = {'a': [1,2,3], 'b': [1.2,2.3,4.5], 'c': [3,4,5]})
#printing specific column
print(df['a'])

print('\n')

#printing specified rows
print(df[1:3])

0    1
1    2
2    3
Name: a, dtype: int64


   a    b  c
1  2  2.3  4
2  3  4.5  5


8. Write a Python program to select the rows the score is between 15 and 20 (inclusive)

In [139]:
exam_data = {'name': ['Anastasia', 'Dima',
'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],'score': [12.5, 9, 16.5,
np.nan, 9, 20, 14.5, np.nan, 8, 19],'attempts': [1,
3, 2, 3, 2, 3, 1, 1, 2, 1],
 'qualify': ['yes', 'no', 'yes', 'no', 'no',
'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
'i', 'j']

data1 = pd.DataFrame(exam_data)
data1

name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [140]:
data1[data1['score'].between(15,20)]

name  score  attempts qualify
2  Katherine   16.5         2     yes
5    Michael   20.0         3     yes
9      Jonas   19.0         1     yes

9. Write a Python program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

In [141]:
data1[(data1['attempts'] < 2) & (data1['score'] > 15)]

name  score  attempts qualify
9  Jonas   19.0         1     yes

10. Write a Python program to append a new row 'k' to Data Frame with given values for each column. Now delete the new row and return the original data frame.

In [142]:
#adding new row
data1.loc['k'] = ['p','q','r', 's']
data1

name score attempts qualify
0  Anastasia  12.5        1     yes
1       Dima     9        3      no
2  Katherine  16.5        2     yes
3      James   NaN        3      no
4      Emily     9        2      no
5    Michael    20        3     yes
6    Matthew  14.5        1     yes
7      Laura   NaN        1      no
8      Kevin     8        2      no
9      Jonas    19        1     yes
k          p     q        r       s

In [143]:
#deleting new row
data1 = data1.drop(['k'], axis=0)
data1

name score attempts qualify
0  Anastasia  12.5        1     yes
1       Dima     9        3      no
2  Katherine  16.5        2     yes
3      James   NaN        3      no
4      Emily     9        2      no
5    Michael    20        3     yes
6    Matthew  14.5        1     yes
7      Laura   NaN        1      no
8      Kevin     8        2      no
9      Jonas    19        1     yes

11. Write a Python program to sort the data frame first by 'name' in descending order, then by 'score' in ascending order

In [144]:
data1.sort_values(by = ['name', 'score'], ascending=[False,True], inplace=True)
data1

name score attempts qualify
5    Michael    20        3     yes
6    Matthew  14.5        1     yes
7      Laura   NaN        1      no
8      Kevin     8        2      no
2  Katherine  16.5        2     yes
9      Jonas    19        1     yes
3      James   NaN        3      no
4      Emily     9        2      no
1       Dima     9        3      no
0  Anastasia  12.5        1     yes

12. Write a Python program to insert a new column in existing DataFrame

In [145]:
data1['new_Col'] = [1,2,3,4,5,6,7,8,9,10]
data1

name score attempts qualify  new_Col
5    Michael    20        3     yes        1
6    Matthew  14.5        1     yes        2
7      Laura   NaN        1      no        3
8      Kevin     8        2      no        4
2  Katherine  16.5        2     yes        5
9      Jonas    19        1     yes        6
3      James   NaN        3      no        7
4      Emily     9        2      no        8
1       Dima     9        3      no        9
0  Anastasia  12.5        1     yes       10

13. Write a Python program to change the name 'James' to 'Suresh' in name column of the data frame

In [146]:
data1['name'] = data1['name'].replace('James', 'Suresh')
data1

name score attempts qualify  new_Col
5    Michael    20        3     yes        1
6    Matthew  14.5        1     yes        2
7      Laura   NaN        1      no        3
8      Kevin     8        2      no        4
2  Katherine  16.5        2     yes        5
9      Jonas    19        1     yes        6
3     Suresh   NaN        3      no        7
4      Emily     9        2      no        8
1       Dima     9        3      no        9
0  Anastasia  12.5        1     yes       10